#!/usr/bin/env python3
"""Embed sms/base-rom/ps_base_rom.sms into src/js/sms_base_rom.js (base64).

Run after every `make` in sms/base-rom:
    python3 sms/tools/embed_base_rom.py
"""
import base64, os, sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
rom_path = os.path.join(root, 'sms', 'base-rom', 'ps_base_rom.sms')
out_path = os.path.join(root, 'src', 'js', 'sms_base_rom.js')

if not os.path.exists(rom_path):
    sys.exit('base ROM not found: %s (run make in sms/base-rom first)' % rom_path)

data = open(rom_path, 'rb').read()
if len(data) != 32768:
    sys.exit('base ROM must be exactly 32768 bytes, got %d' % len(data))

b64 = base64.b64encode(data).decode()
with open(out_path, 'w') as f:
    f.write('/* auto-generated by sms/tools/embed_base_rom.py - do not edit */\n')
    f.write('var PS_SMS_BASE_ROM_B64 = "%s";\n' % b64)
    f.write('if (typeof module !== "undefined" && module.exports) module.exports = PS_SMS_BASE_ROM_B64;\n')
print('wrote %s (%d bytes of ROM)' % (out_path, len(data)))
